export enum OrderStatusEnum {
  NEW = 'NEW',
  CONFIRMED = 'CONFIRMED',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
  PAYMENT_APPROVED = 'PAYMENT_APPROVED',
  IN_PROGRESS = 'IN_PROGRESS',
  READY = 'READY',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
}
